---
permalink: pretty
title: OSH 1911 Microsoft
tagline: an annotated digital edition
description: An annotated digital edition created with <a href="http://readux.library.emory.edu/">Readux</a>
url: 
baseurl: ''
gems:
- jekyll-sitemap
author:
  name: An Author
  url: 
  email: 
  twitter: 
version: 0.7
homepage_image: https://images.readux.ecds.emory.edu:8443/cantaloupe/iiif/2/osh-1911-m_00000012.jpg/full/full/0/default.jpg
show_annotation_author: true
source_info:
  title: OSH 1911 Microsoft
  via_readux: true
publication_info:
  title: OSH 1911 Microsoft
  date: '2019'
  editors: []
image_size:
  page:
    width: 1785
    height: 2220
collections:
  annotations:
    output: true
    permalink: "/annotations/:path/"
  volume_pages:
    output: true
    permalink: "/pages/:path/"
defaults:
- scope:
    path: ''
    type: volume_pages
  values:
    layout: volume_page
    short_label: p.
    deep_zoom: false
    extra_js:
    - volume-page.js
    - hammer.min.js
- scope:
    path: ''
    type: annotations
  values:
    layout: annotation
